CXX = c++
CC = c++

OBJECTS = \
		  Object.o \
		  extra/hud.o \
		  extra/gl_hud.o \
		  viewer.o

CXXFLAGS = -I/opt/local/include
LDFLAGS = -lglut -lGL -lGLU -L/opt/local/lib -lGLEW


default: viewer

viewer: $(OBJECTS)

clean:
	rm -rf viewer $(OBJECTS)
