OBJECTS = \
		  Object.o \
		  extra/hud.o \
		  extra/gl_hud.o \
		  viewer.o

CXXFLAGS = -g -ggdb3
LDFLAGS = -lGL -lglut -lGLEW
default: viewer

viewer: $(OBJECTS)

clean:
	rm -rf viewer $(OBJECTS)
